name: lb_aggregator
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: Evan Summers <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  redis_client: ^0.1.16

dev_dependencies:
  test: ^0.12.0
